### ISSUE TITLE
Incorrect handling of all_request_params

### ISSUE THREAD

**Issue by apdavison** [HumanBrainProject/kg-core-python#6]
`Queries. execute_query_by_id` has an argument `all_request_params`, which is passed on to `_get` in the `params` dict. However, this does not give the correct results. Instead, the keys and values in `all_request_params` should be added individually to `params`.

**Comment by olinux** [comment]
You are absolutely right - we're going to fix this asap.

**Comment by olinux** [comment]
fixed in 0.9.9
